name: Setup tools
description: "Setup tools for the project"

inputs:
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true
    default: "eu-west-1"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "adopt"

    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Install gsemver
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with: # Grab a specific tag
        repo: arnaud-deprez/gsemver
        tag: v0.9.0
