name: Build and deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: aws-dev
    steps:
      - uses: actions/checkout@v4

      - name: Caching
        uses: ./.github/actions/cache

      - name: Setup tools and credentials
        uses: ./.github/actions/setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build
        uses: ./.github/actions/build

      - name: Deploy API and UI
        run: ./pw deploy-both
